version: "1"
services:

  
  
  config-service:
    image: config-service
    ports:
      - "8081:8081"
    networks:
      - turisup-network
    

  eureka-service:
    container_name: eureka-service
    image: eureka-service
    ports:
      - "8761:8761"
    networks:
      - turisup-network
    #depends_on:
     # - config-service
    

#  auth-service:
#    image: auth-service
#    networks:
#      - turisup-network
#    depends_on:
#      - neo4jdb
#      - config-service
#      - eureka-service
#
#  gateway-service:
#    image: auth-service
#    ports:
#      - "8080:8080"
#    networks:
#      - turisup-network
#    depends_on:
#      - neo4jdb
#      - config-service
#      - eureka-service
#
#  neo4jdb:
#    image: neo4j:4.4-community
#    ports:
#      - "7474:7474"
#      - "7687:7687"
#    volumes:
#      - $HOME/neo4j/data:/data
#    networks:
#      - turisup-network
#    environment:
#      - NEO4J_AUTH=none
 

networks:
  turisup-network: 