server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  admin-paths:
    paths:
      - uri: "/auth/login"
        method: "POST"
      - uri: "/auth/validate"
        method: "POST"
      - uri: "/auth/create"
        method: "POST"

spring:
  application:
    name: auth-service
  neo4j:
    uri: bolt://neo4jdb:7687
    authentication:
      username: neo4j
      password: secret
  http:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

jwt:
  secret: secret
  
