server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url: 
      default-zone: http://eureka-service:8761/eureka/

spring:
  http:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  servlet:
      multipart:
        max-file-size: 200MB
        max-request-size: 200MB