server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  admin-paths:
    paths:
      - uri: "/auth/login"
        method: "POST"
      - uri: "/auth/validate"
        method: "POST"
      - uri: "/auth/create"
        method: "POST"
spring:
  application:
    name: auth-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: secret
  cloud:
    config:
      enabled: true
      uri: http://localhost:8081

jwt:
  secret: secret
  
