server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Argos98p/TurisUpMicrosV2.git
          search-paths: config-data/{profile}
  application:
    name: config-service
  profiles:
    active: dev